const nome = 'Yamilla';
const sobrenome = 'Calixto';
const idade = 26;
const peso = 49;
const alturaEmM = 1.66;
let imc; 
let anoNacimento; 
imc = peso /(alturaEmM*alturaEmM);
anoNacimento = 2022-idade;
console.log(`${nome} ${sobrenome} tem ${idade} anos, pesa ${peso} kg.`);
console.log(`Tem ${alturaEmM} de altura e seu IMC é de  ${imc}`);
console.log(`${nome} nasceu em ${anoNacimento}`);